version: '2'
services:
    web:
        build: .
        ports:
            - '8181:80'
            - '8200:8200'
        volumes:
            - './run/log:/var/log/lizmap'

            # Uncomment the next line to mount the directory 'projects' into '/home'
            # - './projects:/home'
